-- LankaExpressway SQL Migration & Seed Data Script
-- Sri Lanka Online Luxury Bus Reservation System
-- Generated for Real Publicly Verified Bus Operator Data

-- 1. Insert Operators
INSERT OR REPLACE INTO operators (id, name, contact_number, email, website, operator_type, service_category, status, source_name, source_url, last_verified_date, data_status, notes) VALUES
('OP-01', 'Superline Travels', '+94 77 738 2186', 'info@superline.lk', 'https://superline.lk', 'Private', 'Super Luxury', 'Active', 'Superline Travels Official Portal & BusSeat.lk', 'https://superline.lk', '2026-08-26', 'Verified', 'Premier Sri Lankan private luxury coach operator running Volvo B11R and Yutong super luxury services across major intercity corridors.'),
('OP-02', 'NCG Express', '+94 77 107 5555', 'info@ncgexpress.lk', 'https://ncgexpress.lk', 'Private', 'Super Luxury', 'Active', 'NCG Express Official Timetable & Magiya.lk', 'https://ncgexpress.lk', '2026-08-26', 'Verified', 'Major long-distance super luxury carrier specializing in Colombo-Jaffna Route 87 and Panadura-Kandy Route 17 high-deck coaches.'),
('OP-03', 'Rathna Travels', '+94 77 335 4555', 'info@rathnatravels.lk', 'https://rathnatravels.lk', 'Private', 'Super Luxury', 'Active', 'Rathna Travels Booking Desk & BusSeat.lk', 'https://rathnatravels.lk', '2026-08-26', 'Verified', 'High-frequency Northern corridor luxury bus provider connecting Colombo with Vavuniya, Mannar, Anuradhapura and Jaffna.'),
('OP-04', 'Dinisuru Super Line', '+94 77 832 1122', 'info@dinisuru.lk', 'https://magiya.lk', 'Private', 'Luxury', 'Active', 'Magiya.lk Verified Operators Directory', 'https://magiya.lk', '2026-08-26', 'Verified', 'Operates scheduled AC luxury buses connecting Colombo to North Central Province (Anuradhapura, Dambulla, Kurunegala).'),
('OP-05', 'Southern Highway Express (MMC Network)', '+94 11 203 4477', 'info@mmck.lk', 'https://mmck.lk', 'Public', 'Luxury', 'Active', 'Makumbura Multimodal Centre (MMCK) & National Transport Commission (NTC)', 'https://www.ntc.gov.lk', '2026-08-26', 'Verified', 'Regulated expressway bus network operating direct non-stop luxury services via Southern Expressway E01 and Central Expressway E04.'),
('OP-06', 'SPS Travels & Bastian Express', '+94 77 712 3499', 'booking@spstravels.lk', 'https://www.busseat.lk', 'Private', 'Super Luxury', 'Active', 'BusSeat.lk Eastern Corridor Directory', 'https://www.busseat.lk', '2026-08-26', 'Verified', 'Super luxury overnight and day coach services linking Colombo with Eastern Province hubs (Batticaloa, Trincomalee, Akkaraipattu).'),
('OP-07', 'North West Express', '+94 77 555 1533', 'contact@northwestexpress.lk', 'https://www.busseat.lk', 'Private', 'Premium', 'Active', 'BusSeat.lk VIP Sleeper Booking Platform', 'https://www.busseat.lk', '2026-08-26', 'Verified', 'Operates 2+1 VIP executive sleeper and semi-sleeper luxury coaches between Colombo, Vavuniya, Mannar and Jaffna.');

-- 2. Insert Routes
INSERT OR REPLACE INTO routes (id, route_no, name, from_city, to_city, boarding_points, dropping_points, highway_route, distance_km, toll_fee, status, source_name, source_url, last_verified_date, data_status, notes) VALUES
('R-01', 'EX 1-1', 'Colombo - Galle Expressway Direct', 'Colombo (Makumbura)', 'Galle (MMC)', '["Makumbura Multimodal Center (Kottawa)","Kottawa Interchange Terminal"]', '["Pinnaduwa Interchange","Galle Multimodal Bus Center"]', 'Southern Expressway (E01)', '116 km', 420, 'Active', 'National Transport Commission (NTC) & MMCK', 'https://www.ntc.gov.lk', '2026-08-26', 'Verified', 'High-frequency luxury service via E01 Southern Expressway.'),
('R-02', 'EX 1-2', 'Colombo - Matara Expressway Direct', 'Colombo (Makumbura)', 'Matara (MMC)', '["Makumbura Multimodal Center (Kottawa)","Kahathuduwa Exit Point"]', '["Godagama Interchange","Matara Main Bus Stand (MMC)"]', 'Southern Expressway (E01)', '158 km', 550, 'Active', 'National Transport Commission (NTC)', 'https://www.ntc.gov.lk', '2026-08-26', 'Verified', 'Direct expressway route taking approximately 2 hours.'),
('R-03', 'EX 2-1', 'Colombo - Hambantota / Tangalle Expressway', 'Colombo (Makumbura)', 'Hambantota', '["Makumbura Multimodal Center (Kottawa)"]', '["Beliatta Interchange","Tangalle City Halt","Hambantota Admin Complex"]', 'Southern Expressway (E01 Extension)', '220 km', 750, 'Active', 'MMCK Bus Operations Desk', 'https://mmck.lk', '2026-08-26', 'Verified', 'Expressway transit to southern deep-water port and commercial hub.'),
('R-04', 'EX 2-2', 'Colombo - Kataragama Sacred City Express', 'Colombo (Makumbura)', 'Kataragama', '["Makumbura Multimodal Center (Kottawa)"]', '["Mattala Exit","Tissamaharama Clock Tower","Kataragama Main Bus Stand"]', 'Southern Expressway (E01)', '260 km', 850, 'Active', 'NTC Inter-Provincial Schedule', 'https://www.ntc.gov.lk', '2026-08-26', 'Verified', 'Popular pilgrim and cultural tourist expressway coach service.'),
('R-05', 'EX 4-1', 'Kadawatha - Kandy Expressway & Intercity', 'Kadawatha (KMC)', 'Kandy (Goods Shed)', '["Kadawatha Multimodal Center (KMC)","Mirigama Expressway Entrance"]', '["Peradeniya Junction","Kandy Goods Shed Bus Terminal"]', 'Central Expressway (E04) / A1', '105 km', 350, 'Active', 'Kadawatha Multimodal Center & NTC', 'https://www.ntc.gov.lk', '2026-08-26', 'Verified', 'Direct luxury coach connection between Western and Central province.'),
('R-06', 'EX 2-34', 'Colombo - Badulla Hill Country Super Express', 'Colombo (Makumbura)', 'Badulla', '["Makumbura Multimodal Center (Kottawa)"]', '["Beragala Junction","Bandarawela Bus Stand","Badulla Main Terminal"]', 'Southern Expressway / Route 99', '230 km', 450, 'Active', 'NCG Express & Superline Official Schedules', 'https://superline.lk', '2026-08-26', 'Verified', 'Scenic luxury coach via Southern Expressway and Southern hill crests.'),
('R-07', 'Route 87', 'Colombo - Jaffna Northern Highway Super Luxury', 'Colombo (Bastian Mawatha)', 'Jaffna', '["Wellawatta (Ramakrishna Rd)","Colombo Bastian Mawatha (Pettah)","Kadawatha Exit"]', '["Vavuniya Central","Kilinochchi Town","Jaffna Central Bus Stand"]', 'A9 Northern Highway', '395 km', 0, 'Active', 'BusSeat.lk & NCG Express & Superline', 'https://www.busseat.lk', '2026-08-26', 'Verified', 'High-demand overnight and morning luxury corridor across Sri Lanka.'),
('R-08', 'Route 49', 'Colombo - Trincomalee East Coast Express', 'Colombo (Bastian Mawatha)', 'Trincomalee', '["Colombo Bastian Mawatha","Kurunegala Interchange","Habarana Junction"]', '["Kantale Town","Trincomalee Town Bus Terminal"]', 'A6 Highway', '260 km', 0, 'Active', 'Superline Travels & BusSeat.lk', 'https://superline.lk', '2026-08-26', 'Verified', 'Popular tourist and port city super luxury service.'),
('R-09', 'Route 48', 'Colombo - Batticaloa Eastern Sunrise Luxury', 'Colombo (Bastian Mawatha)', 'Batticaloa', '["Colombo Bastian Mawatha (Pettah)","Wellawatta Superline Office","Kaduwela Junction"]', '["Polonnaruwa Cut-off","Valaichchenai","Batticaloa Clock Tower Bus Stand"]', 'A4 / A11 Highway', '315 km', 0, 'Active', 'SPS Travels & Superline Official Portals', 'https://www.busseat.lk', '2026-08-26', 'Verified', 'Direct overnight luxury bus to Batticaloa and Eastern towns.'),
('R-10', 'Route 57', 'Colombo - Anuradhapura Ancient Capital AC Express', 'Colombo (Bastian Mawatha)', 'Anuradhapura', '["Colombo Bastian Mawatha (Pettah)","Negombo Katunayake Junction","Puttalam Bridge"]', '["Tambuttegama","Anuradhapura Old Bus Stand","New Town Bus Stand"]', 'A8 / Puttalam Highway', '205 km', 0, 'Active', 'Dinisuru Super Line & Rathna Travels via Magiya.lk', 'https://magiya.lk', '2026-08-26', 'Verified', 'Cultural triangle air-conditioned luxury express service.'),
('R-11', 'Route 48-1', 'Colombo - Dambulla / Sigiriya Cultural Route', 'Colombo (Bastian Mawatha)', 'Dambulla', '["Colombo Bastian Mawatha","Nittambuwa Junction","Kurunegala Central"]', '["Ibbagamuwa","Dambulla Main Economic Center & Bus Stand"]', 'A6 Kandy-Jaffna Highway', '160 km', 0, 'Active', 'BusSeat.lk & Magiya.lk', 'https://www.busseat.lk', '2026-08-26', 'Verified', 'Popular gateway to Sigiriya fortress and world heritage sites.'),
('R-12', 'Route 04', 'Colombo - Mannar Coastal Express', 'Colombo (Bastian Mawatha)', 'Mannar', '["Colombo Bastian Mawatha","Kochchikade","Puttalam","Medawachchiya"]', '["Murunkan","Thalaimannar Pier Road","Mannar Town Bus Stand"]', 'Medawachchiya-Talaimannar Highway (A14)', '310 km', 0, 'Active', 'Rathna Travels & North West Express', 'https://rathnatravels.lk', '2026-08-26', 'Verified', 'Connects western capital to historic Mannar Island.'),
('R-13', 'Route 87-V', 'Colombo - Vavuniya Express', 'Colombo (Bastian Mawatha)', 'Vavuniya', '["Colombo Bastian Mawatha","Kurunegala Bypass","Anuradhapura Outer Circular"]', '["Vavuniya Central Terminal","Kandy Road Junction"]', 'A9 Highway', '255 km', 0, 'Active', 'BusSeat.lk & Rathna Travels', 'https://www.busseat.lk', '2026-08-26', 'Verified', 'Northern gate city passenger connection.');

-- 3. Insert Buses
INSERT OR REPLACE INTO buses (id, operator_id, bus_no, name, model, bus_type, service_category, seat_layout, total_seats, facilities, rating, status, source_name, source_url, last_verified_date, data_status, notes) VALUES
('B-01', 'OP-01', 'WP ND-6821', 'Superline Royal Platinum Coach', 'Volvo B11R Multi-Axle Luxury Coach', 'Super Luxury Volvo', 'Super Luxury', '2+2', 40, '["Air Conditioning","Reclining Seats","USB Charging","Wi-Fi","TV / Video Entertainment","Luggage Space","Complimentary Water Bottle"]', 4.9, 'Active', 'Superline Travels Official Fleet', 'https://superline.lk', '2026-08-26', 'Verified', 'Top-tier luxury Volvo coach with air suspension and pneumatic reclining leather seats.'),
('B-02', 'OP-01', 'WP ND-7194', 'Superline VIP Sleeper Liner', 'Yutong ZK6122H VIP Executive', 'Super Luxury Sleeper (2+1)', 'Premium', '2+1', 28, '["Air Conditioning","Reclining Sleep Seats","Individual USB Charging","Wi-Fi","Entertainment Screen","Blankets","Luggage Space"]', 4.9, 'Active', 'Superline Travels Official Fleet & BusSeat.lk', 'https://superline.lk', '2026-08-26', 'Verified', '2+1 VIP executive layout with single luxury armchairs on the left and pairs on the right.'),
('B-03', 'OP-02', 'WP NB-9245', 'NCG Royal Cruiser', 'Yutong ZK6122H Super Luxury Coach', 'Super Luxury Coach', 'Super Luxury', '2+2', 44, '["Air Conditioning","Reclining Seats","USB Charging","Wi-Fi","Central Audio/Video","Luggage Space"]', 4.8, 'Active', 'NCG Express Official Portals', 'https://ncgexpress.lk', '2026-08-26', 'Verified', 'High-deck super luxury coach with climate control and GPS live tracking.'),
('B-04', 'OP-03', 'NP ND-4412', 'Rathna Northern Star', 'Ashok Leyland Viking 222 AC Coach', 'Luxury AC', 'Luxury', '2+2', 40, '["Air Conditioning","Reclining Seats","USB Charging","Reading Lights","Luggage Space"]', 4.6, 'Active', 'Rathna Travels Fleet', 'https://rathnatravels.lk', '2026-08-26', 'Verified', 'Comfortable air-conditioned intercity coach tailored for long-distance highway travel.'),
('B-05', 'OP-04', 'WP NC-3318', 'Dinisuru Highway Breeze', 'Higer KLQ6129 Luxury AC', 'Luxury AC', 'Luxury', '2+2', 42, '["Air Conditioning","Reclining Seats","USB Charging","Overhead Luggage Rack","Curtains"]', 4.5, 'Active', 'Magiya.lk Fleet Directory', 'https://magiya.lk', '2026-08-26', 'Verified', 'Reliable air-conditioned intercity luxury coach with spacious underfloor luggage hold.'),
('B-06', 'OP-05', 'SP ND-5521', 'Southern Expressway Galle Liner', 'King Long XMQ6129 Highway Coach', 'Expressway Luxury AC', 'Luxury', '2+2', 40, '["Air Conditioning","Reclining Seats","Expressway Toll Paid","Luggage Boot","CCTV Security"]', 4.7, 'Active', 'Makumbura Multimodal Center (MMCK)', 'https://mmck.lk', '2026-08-26', 'Verified', 'Dedicated Southern Expressway non-stop direct shuttle coach.'),
('B-07', 'OP-05', 'SP ND-8834', 'Southern Expressway Matara Flyer', 'King Long XMQ6129 Highway Coach', 'Expressway Luxury AC', 'Luxury', '2+2', 40, '["Air Conditioning","Reclining Seats","Expressway Toll Paid","Luggage Boot"]', 4.7, 'Active', 'Makumbura Multimodal Center (MMCK)', 'https://mmck.lk', '2026-08-26', 'Verified', 'Frequent expressway service on the Makumbura-Matara corridor.'),
('B-08', 'OP-06', 'EP ND-2910', 'SPS Eastern Monarch', 'Yutong ZK6122H Super Luxury', 'Super Luxury Coach', 'Super Luxury', '2+2', 40, '["Air Conditioning","Reclining Seats","USB Charging","Wi-Fi","TV","Luggage Space","Complimentary Water"]', 4.8, 'Active', 'BusSeat.lk Verified Listing', 'https://www.busseat.lk', '2026-08-26', 'Verified', 'Super luxury overnight long-distance cruiser with luxury headrests.'),
('B-09', 'OP-07', 'NP ND-8102', 'North West VIP Crown Class', 'Volvo B11R 2+1 Executive Suite', 'Super Luxury Sleeper (2+1)', 'Premium', '2+1', 28, '["Air Conditioning","VIP Single / Pair Sleeper Recliners","Personal USB Charging","Wi-Fi","Reading Lights","Blankets","Spacious Luggage Hold"]', 4.9, 'Active', 'BusSeat.lk VIP Category', 'https://www.busseat.lk', '2026-08-26', 'Verified', 'Exclusive 28-seat 2+1 VIP executive configuration with extra legroom and semi-sleeper capability.'),
('B-10', 'OP-05', 'CP ND-1980', 'Central Expressway Kandy Royal', 'Higer KLQ6119 AC Coach', 'Expressway Luxury AC', 'Luxury', '2+2', 40, '["Air Conditioning","Reclining Seats","USB Charging","Luggage Compartment"]', 4.6, 'Active', 'National Transport Commission (NTC)', 'https://www.ntc.gov.lk', '2026-08-26', 'Verified', 'High-comfort coach connecting Kadawatha Multimodal Center with Kandy Goods Shed.');

-- 4. Insert Schedules
INSERT OR REPLACE INTO schedules (id, bus_id, route_id, departure_time, arrival_time, duration, operating_days, fare, currency, online_booking, e_ticket_supported, qr_ticket_supported, reserved_seats, status, source_name, source_url, last_verified_date, data_status, notes) VALUES
('S-01', 'B-06', 'R-01', '06:30 AM', '08:00 AM', '1h 30m', 'Daily', 420, 'LKR', 1, 1, 1, '["A1","A2","B3","B4"]', 'Active', 'MMCK & NTC Official Fare Schedule', 'https://www.ntc.gov.lk', '2026-08-26', 'Verified', 'Early morning express via Southern Expressway E01.'),
('S-02', 'B-06', 'R-01', '09:00 AM', '10:30 AM', '1h 30m', 'Daily', 420, 'LKR', 1, 1, 1, '["C1","C2","D5"]', 'Active', 'MMCK Daily Operations', 'https://mmck.lk', '2026-08-26', 'Verified', 'Mid-morning expressway service.'),
('S-03', 'B-01', 'R-01', '15:00 PM', '16:30 PM', '1h 30m', 'Daily', 750, 'LKR', 1, 1, 1, '[]', 'Active', 'Superline Travels Expressway Division', 'https://superline.lk', '2026-08-26', 'Verified', 'Superline Volvo Luxury direct service to Galle MMC.'),
('S-04', 'B-07', 'R-02', '07:15 AM', '09:15 AM', '2h 00m', 'Daily', 550, 'LKR', 1, 1, 1, '["A3","A4","B10"]', 'Active', 'NTC Expressway Schedule', 'https://www.ntc.gov.lk', '2026-08-26', 'Verified', 'Direct 2-hour expressway transit to Matara.'),
('S-05', 'B-07', 'R-02', '16:30 PM', '18:30 PM', '2h 00m', 'Daily', 550, 'LKR', 1, 1, 1, '["C5","D5"]', 'Active', 'NTC Expressway Schedule', 'https://www.ntc.gov.lk', '2026-08-26', 'Verified', 'Evening return expressway commuter service.'),
('S-06', 'B-01', 'R-03', '08:00 AM', '11:15 AM', '3h 15m', 'Daily', 950, 'LKR', 1, 1, 1, '["A1","A2","C1","C2"]', 'Active', 'MMCK Long-Distance Timetable', 'https://mmck.lk', '2026-08-26', 'Verified', 'Superline Volvo through Southern Expressway E01 Ext.'),
('S-07', 'B-03', 'R-04', '06:00 AM', '09:45 AM', '3h 45m', 'Daily', 1150, 'LKR', 1, 1, 1, '["B1","B2"]', 'Active', 'NCG Express Sacred City Route', 'https://ncgexpress.lk', '2026-08-26', 'Verified', 'Early morning express coach directly into Kataragama.'),
('S-08', 'B-10', 'R-05', '06:15 AM', '08:45 AM', '2h 30m', 'Daily', 650, 'LKR', 1, 1, 1, '["A5","B5"]', 'Active', 'Kadawatha Multimodal Center Information Desk', 'https://www.ntc.gov.lk', '2026-08-26', 'Verified', 'Morning executive transit via Central Expressway E04.'),
('S-09', 'B-10', 'R-05', '13:30 PM', '16:00 PM', '2h 30m', 'Daily', 650, 'LKR', 1, 1, 1, '[]', 'Active', 'Kadawatha Multimodal Center Information Desk', 'https://www.ntc.gov.lk', '2026-08-26', 'Verified', 'Afternoon departure to Kandy Goods Shed.'),
('S-10', 'B-03', 'R-07', '20:30 PM', '05:00 AM', '8h 30m', 'Daily', 3200, 'LKR', 1, 1, 1, '["A1","A2","A3","B1","B2","B3"]', 'Active', 'NCG Express Route 87 Official Schedule', 'https://ncgexpress.lk', '2026-08-26', 'Verified', 'Overnight Super Luxury coach via A9 Highway to Jaffna Central.'),
('S-11', 'B-02', 'R-07', '21:15 PM', '05:45 AM', '8h 30m', 'Daily', 3500, 'LKR', 1, 1, 1, '["A1","A2","B1","C1"]', 'Active', 'Superline Travels VIP Sleeper Schedule', 'https://superline.lk', '2026-08-26', 'Verified', '2+1 VIP Sleeper luxury service with blankets and reclining sleep seats.'),
('S-12', 'B-09', 'R-07', '07:30 AM', '16:00 PM', '8h 30m', 'Daily', 3400, 'LKR', 1, 1, 1, '["A4","B4"]', 'Active', 'North West Express via BusSeat.lk', 'https://www.busseat.lk', '2026-08-26', 'Verified', 'Daytime 2+1 VIP luxury executive coach to Jaffna.'),
('S-13', 'B-01', 'R-08', '21:30 PM', '03:30 AM', '6h 00m', 'Daily', 2400, 'LKR', 1, 1, 1, '["A1","A2"]', 'Active', 'Superline Travels Trincomalee Schedule', 'https://superline.lk', '2026-08-26', 'Verified', 'Volvo Super Luxury overnight direct to Trincomalee port city.'),
('S-14', 'B-08', 'R-09', '20:45 PM', '04:15 AM', '7h 30m', 'Daily', 2600, 'LKR', 1, 1, 1, '["C3","D3"]', 'Active', 'SPS Travels Eastern Directory & BusSeat.lk', 'https://www.busseat.lk', '2026-08-26', 'Verified', 'Super Luxury overnight coach to Batticaloa Clock Tower.'),
('S-15', 'B-05', 'R-10', '05:30 AM', '10:00 AM', '4h 30m', 'Daily', 1800, 'LKR', 1, 1, 1, '["A2","B2"]', 'Active', 'Dinisuru Super Line via Magiya.lk', 'https://magiya.lk', '2026-08-26', 'Verified', 'Morning air-conditioned express to Anuradhapura sacred city.'),
('S-16', 'B-04', 'R-11', '06:45 AM', '10:30 AM', '3h 45m', 'Daily', 1450, 'LKR', 1, 1, 1, '[]', 'Active', 'Rathna Travels & BusSeat.lk', 'https://rathnatravels.lk', '2026-08-26', 'Verified', 'Comfortable morning AC coach to Dambulla & Sigiriya junction.'),
('S-17', 'B-04', 'R-12', '21:00 PM', '04:00 AM', '7h 00m', 'Daily', 2750, 'LKR', 1, 1, 1, '["A6","B6"]', 'Active', 'Rathna Travels Northern Routes', 'https://rathnatravels.lk', '2026-08-26', 'Verified', 'Overnight luxury coach directly serving Mannar island.'),
('S-18', 'B-03', 'R-13', '14:00 PM', '19:30 PM', '5h 30m', 'Daily', 2100, 'LKR', 1, 1, 1, '[]', 'Active', 'NCG Express Route 87 Sub-Service', 'https://ncgexpress.lk', '2026-08-26', 'Verified', 'Afternoon luxury AC service to Vavuniya Central Terminal.'),
('S-19', 'B-01', 'R-06', '07:00 AM', '11:30 AM', '4h 30m', 'Daily', 1950, 'LKR', 1, 1, 1, '["A1","A2"]', 'Active', 'Superline Travels Hill Country Schedule', 'https://superline.lk', '2026-08-26', 'Verified', 'Volvo Super Luxury via Southern Expressway to Bandarawela & Badulla.');
