export const verifiedOperators = [
  {
    operatorId: 'OP-01',
    name: 'Superline Travels',
    contactNumber: '+94 77 738 2186',
    email: 'info@superline.lk',
    website: 'https://superline.lk',
    operatorType: 'Private',
    serviceCategory: 'Super Luxury',
    status: 'Active',
    sourceName: 'Superline.lk & BusSeat.lk',
    sourceUrl: 'https://superline.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Premier Sri Lankan private luxury coach line operating Volvo B11R & Yutong 2+1 VIP sleepers.',
  },
  {
    operatorId: 'OP-02',
    name: 'NCG Express',
    contactNumber: '+94 77 107 5555',
    email: 'info@ncgexpress.lk',
    website: 'https://ncgexpress.lk',
    operatorType: 'Private',
    serviceCategory: 'Super Luxury',
    status: 'Active',
    sourceName: 'NCG Express Official & Magiya.lk',
    sourceUrl: 'https://ncgexpress.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Major long-distance carrier specializing in Northern and Eastern highway routes.',
  },
  {
    operatorId: 'OP-03',
    name: 'Rathna Travels',
    contactNumber: '077 335 4555',
    email: 'info@rathnatravels.lk',
    website: 'https://rathnatravels.lk',
    operatorType: 'Private',
    serviceCategory: 'Super Luxury',
    status: 'Active',
    sourceName: 'Rathna Travels & BusSeat.lk',
    sourceUrl: 'https://rathnatravels.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'High-frequency luxury services across Northern & Central corridors.',
  },
  {
    operatorId: 'OP-04',
    name: 'Dinisuru Super Line',
    contactNumber: '077 832 1122',
    email: 'contact@dinisuru.lk',
    website: 'https://magiya.lk',
    operatorType: 'Private',
    serviceCategory: 'Luxury',
    status: 'Active',
    sourceName: 'Magiya.lk Public Transport Portal',
    sourceUrl: 'https://magiya.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Pioneer air-conditioned express coach line on Anuradhapura & Northern routes.',
  },
  {
    operatorId: 'OP-05',
    name: 'Southern Highway Express (MMCK Network)',
    contactNumber: '011 203 4477',
    email: 'help@mmck.lk',
    website: 'https://mmck.lk',
    operatorType: 'Public',
    serviceCategory: 'Luxury',
    status: 'Active',
    sourceName: 'Makumbura Multimodal Center (MMCK) & NTC',
    sourceUrl: 'https://mmck.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Official Southern Expressway bus consortium departing from Makumbura Multimodal Hub.',
  },
  {
    operatorId: 'OP-06',
    name: 'SPS Travels & Bastian Express',
    contactNumber: '077 712 3499',
    email: 'reservations@spstravels.lk',
    website: 'https://www.busseat.lk',
    operatorType: 'Private',
    serviceCategory: 'Super Luxury',
    status: 'Active',
    sourceName: 'BusSeat.lk & NTC Schedule',
    sourceUrl: 'https://www.busseat.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Specialized luxury long-distance service for Colombo-Batticaloa & Eastern Province.',
  },
  {
    operatorId: 'OP-07',
    name: 'North West Express',
    contactNumber: '077 555 1533',
    email: 'info@northwestexpress.lk',
    website: 'https://www.busseat.lk',
    operatorType: 'Private',
    serviceCategory: 'Premium',
    status: 'Active',
    sourceName: 'BusSeat.lk Verified Listing',
    sourceUrl: 'https://www.busseat.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '2+1 VIP Crown Class sleeper coaches operating on long-distance Northern routes.',
  },
];

export const verifiedRoutes = [
  {
    routeId: 'R-01',
    routeNo: 'EX 1-1',
    name: 'Colombo (Makumbura) - Galle Expressway Direct',
    fromCity: 'Colombo (Makumbura)',
    toCity: 'Galle (MMC)',
    boardingPoints: ['Makumbura Multimodal Center', 'Kottawa Interchange'],
    droppingPoints: ['Galle Central Terminal', 'Karapitiya Junction'],
    highwayRoute: 'Southern Expressway (E01)',
    distanceKm: '116 km',
    tollFee: 420,
    status: 'Active',
    sourceName: 'NTC Official Expressway Timetable',
    sourceUrl: 'https://www.ntc.gov.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Direct 1h 30m expressway transit.',
  },
  {
    routeId: 'R-01-R',
    routeNo: 'EX 1-1-R',
    name: 'Galle (MMC) - Colombo (Makumbura) Expressway Direct',
    fromCity: 'Galle (MMC)',
    toCity: 'Colombo (Makumbura)',
    boardingPoints: ['Galle Central Terminal', 'Karapitiya Junction'],
    droppingPoints: ['Makumbura Multimodal Center', 'Kottawa Interchange'],
    highwayRoute: 'Southern Expressway (E01)',
    distanceKm: '116 km',
    tollFee: 420,
    status: 'Active',
    sourceName: 'NTC Official Expressway Timetable',
    sourceUrl: 'https://www.ntc.gov.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Return 1h 30m expressway transit.',
  },
  {
    routeId: 'R-02',
    routeNo: 'EX 1-2',
    name: 'Colombo (Makumbura) - Matara Expressway Direct',
    fromCity: 'Colombo (Makumbura)',
    toCity: 'Matara (MMC)',
    boardingPoints: ['Makumbura Multimodal Center'],
    droppingPoints: ['Matara Multimodal Center', 'Walmadama Junction'],
    highwayRoute: 'Southern Expressway (E01)',
    distanceKm: '158 km',
    tollFee: 550,
    status: 'Active',
    sourceName: 'NTC Official Timetable',
    sourceUrl: 'https://www.ntc.gov.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Direct 2h 00m expressway transit.',
  },
  {
    routeId: 'R-02-R',
    routeNo: 'EX 1-2-R',
    name: 'Matara (MMC) - Colombo (Makumbura) Expressway Direct',
    fromCity: 'Matara (MMC)',
    toCity: 'Colombo (Makumbura)',
    boardingPoints: ['Matara Multimodal Center', 'Walmadama Junction'],
    droppingPoints: ['Makumbura Multimodal Center'],
    highwayRoute: 'Southern Expressway (E01)',
    distanceKm: '158 km',
    tollFee: 550,
    status: 'Active',
    sourceName: 'NTC Official Timetable',
    sourceUrl: 'https://www.ntc.gov.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Return 2h 00m expressway transit.',
  },
  {
    routeId: 'R-03',
    routeNo: 'EX 2-1',
    name: 'Colombo (Makumbura) - Hambantota Expressway',
    fromCity: 'Colombo (Makumbura)',
    toCity: 'Hambantota',
    boardingPoints: ['Makumbura Multimodal Center'],
    droppingPoints: ['Hambantota Bus Stand', 'Mirijjawila Junction'],
    highwayRoute: 'Southern Expressway Extension (E01)',
    distanceKm: '220 km',
    tollFee: 750,
    status: 'Active',
    sourceName: 'Makumbura MMC Official Schedule',
    sourceUrl: 'https://mmck.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Direct 3h 00m highway route.',
  },
  {
    routeId: 'R-04',
    routeNo: 'EX 2-2',
    name: 'Colombo (Makumbura) - Kataragama Expressway',
    fromCity: 'Colombo (Makumbura)',
    toCity: 'Kataragama',
    boardingPoints: ['Makumbura Multimodal Center'],
    droppingPoints: ['Tissamaharama Bus Stand', 'Kataragama Terminal'],
    highwayRoute: 'Southern Expressway (E01)',
    distanceKm: '260 km',
    tollFee: 850,
    status: 'Active',
    sourceName: 'NTC Schedule & MMCK',
    sourceUrl: 'https://www.ntc.gov.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Direct 3h 45m pilgrim & tourist corridor.',
  },
  {
    routeId: 'R-05',
    routeNo: 'EX 4-1',
    name: 'Kadawatha - Kandy Expressway / Intercity',
    fromCity: 'Kadawatha (KMC)',
    toCity: 'Kandy (Goods Shed)',
    boardingPoints: ['Kadawatha Multimodal Hub'],
    droppingPoints: ['Peradeniya Junction', 'Kandy Goods Shed Terminal'],
    highwayRoute: 'Central Expressway (E04) & A1 Corridor',
    distanceKm: '105 km',
    tollFee: 350,
    status: 'Active',
    sourceName: 'NTC Schedule',
    sourceUrl: 'https://www.ntc.gov.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '2h 30m central corridor.',
  },
  {
    routeId: 'R-05-R',
    routeNo: 'EX 4-1-R',
    name: 'Kandy (Goods Shed) - Kadawatha Expressway / Intercity',
    fromCity: 'Kandy (Goods Shed)',
    toCity: 'Kadawatha (KMC)',
    boardingPoints: ['Kandy Goods Shed Terminal', 'Peradeniya Junction'],
    droppingPoints: ['Kadawatha Multimodal Hub'],
    highwayRoute: 'Central Expressway (E04) & A1 Corridor',
    distanceKm: '105 km',
    tollFee: 350,
    status: 'Active',
    sourceName: 'NTC Schedule',
    sourceUrl: 'https://www.ntc.gov.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Return 2h 30m central corridor.',
  },
  {
    routeId: 'R-06',
    routeNo: 'EX 2-34',
    name: 'Colombo (Makumbura) - Badulla Highway',
    fromCity: 'Colombo (Makumbura)',
    toCity: 'Badulla',
    boardingPoints: ['Makumbura Multimodal Center'],
    droppingPoints: ['Bandarawela Bus Stand', 'Badulla Central Terminal'],
    highwayRoute: 'Southern Expressway & Route 99 Corridor',
    distanceKm: '230 km',
    tollFee: 450,
    status: 'Active',
    sourceName: 'Superline Travels Schedule',
    sourceUrl: 'https://superline.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Scenic 5h 30m hill-country express route.',
  },
  {
    routeId: 'R-06-R',
    routeNo: 'EX 2-34-R',
    name: 'Badulla - Colombo (Makumbura) Highway',
    fromCity: 'Badulla',
    toCity: 'Colombo (Makumbura)',
    boardingPoints: ['Badulla Central Terminal', 'Bandarawela Bus Stand'],
    droppingPoints: ['Makumbura Multimodal Center'],
    highwayRoute: 'Southern Expressway & Route 99 Corridor',
    distanceKm: '230 km',
    tollFee: 450,
    status: 'Active',
    sourceName: 'Superline Travels Schedule',
    sourceUrl: 'https://superline.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Return 5h 30m hill-country express route.',
  },
  {
    routeId: 'R-07',
    routeNo: 'Route 87',
    name: 'Colombo (Bastian Mawatha) - Jaffna Northern Highway',
    fromCity: 'Colombo (Bastian Mawatha)',
    toCity: 'Jaffna',
    boardingPoints: ['Wellawatta Supermarket', 'Bastian Mawatha Terminal'],
    droppingPoints: ['Vavuniya Central', 'Kilinochchi', 'Jaffna Central Stand'],
    highwayRoute: 'A9 Northern Highway',
    distanceKm: '395 km',
    tollFee: 0,
    status: 'Active',
    sourceName: 'BusSeat.lk & NCG Express',
    sourceUrl: 'https://ncgexpress.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '7h 30m luxury sleeper & AC coach service.',
  },
  {
    routeId: 'R-07-R',
    routeNo: 'Route 87-R',
    name: 'Jaffna - Colombo (Bastian Mawatha) Northern Highway',
    fromCity: 'Jaffna',
    toCity: 'Colombo (Bastian Mawatha)',
    boardingPoints: ['Jaffna Central Stand', 'Kilinochchi', 'Vavuniya Central'],
    droppingPoints: ['Bastian Mawatha Terminal', 'Wellawatta Supermarket'],
    highwayRoute: 'A9 Northern Highway',
    distanceKm: '395 km',
    tollFee: 0,
    status: 'Active',
    sourceName: 'BusSeat.lk & NCG Express',
    sourceUrl: 'https://ncgexpress.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Return 7h 30m luxury sleeper & AC coach service.',
  },
  {
    routeId: 'R-08',
    routeNo: 'Route 49',
    name: 'Colombo (Bastian Mawatha) - Trincomalee',
    fromCity: 'Colombo (Bastian Mawatha)',
    toCity: 'Trincomalee',
    boardingPoints: ['Bastian Mawatha Terminal'],
    droppingPoints: ['Habarana Junction', 'Kantale', 'Trincomalee Terminal'],
    highwayRoute: 'A6 Highway',
    distanceKm: '260 km',
    tollFee: 0,
    status: 'Active',
    sourceName: 'Superline.lk & BusSeat.lk',
    sourceUrl: 'https://superline.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '5h 30m overnight & daytime express.',
  },
  {
    routeId: 'R-08-R',
    routeNo: 'Route 49-R',
    name: 'Trincomalee - Colombo (Bastian Mawatha)',
    fromCity: 'Trincomalee',
    toCity: 'Colombo (Bastian Mawatha)',
    boardingPoints: ['Trincomalee Terminal', 'Kantale', 'Habarana Junction'],
    droppingPoints: ['Bastian Mawatha Terminal'],
    highwayRoute: 'A6 Highway',
    distanceKm: '260 km',
    tollFee: 0,
    status: 'Active',
    sourceName: 'Superline.lk & BusSeat.lk',
    sourceUrl: 'https://superline.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Return 5h 30m express route.',
  },
  {
    routeId: 'R-09',
    routeNo: 'Route 48',
    name: 'Colombo (Bastian Mawatha) - Batticaloa',
    fromCity: 'Colombo (Bastian Mawatha)',
    toCity: 'Batticaloa',
    boardingPoints: ['Bastian Mawatha Terminal'],
    droppingPoints: ['Polonnaruwa', 'Valachchenai', 'Batticaloa Central'],
    highwayRoute: 'A4 / A11 Highway',
    distanceKm: '315 km',
    tollFee: 0,
    status: 'Active',
    sourceName: 'SPS Travels & BusSeat.lk',
    sourceUrl: 'https://www.busseat.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '6h 30m Eastern express route.',
  },
  {
    routeId: 'R-09-R',
    routeNo: 'Route 48-R',
    name: 'Batticaloa - Colombo (Bastian Mawatha)',
    fromCity: 'Batticaloa',
    toCity: 'Colombo (Bastian Mawatha)',
    boardingPoints: ['Batticaloa Central', 'Valachchenai', 'Polonnaruwa'],
    droppingPoints: ['Bastian Mawatha Terminal'],
    highwayRoute: 'A4 / A11 Highway',
    distanceKm: '315 km',
    tollFee: 0,
    status: 'Active',
    sourceName: 'SPS Travels & BusSeat.lk',
    sourceUrl: 'https://www.busseat.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Return 6h 30m Eastern express route.',
  },
  {
    routeId: 'R-10',
    routeNo: 'Route 57',
    name: 'Colombo (Bastian Mawatha) - Anuradhapura',
    fromCity: 'Colombo (Bastian Mawatha)',
    toCity: 'Anuradhapura',
    boardingPoints: ['Bastian Mawatha Terminal'],
    droppingPoints: ['Puttalam', 'Anuradhapura New Town Terminal'],
    highwayRoute: 'A8 / Puttalam Corridor',
    distanceKm: '205 km',
    tollFee: 0,
    status: 'Active',
    sourceName: 'Magiya.lk & Dinisuru Line',
    sourceUrl: 'https://magiya.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '4h 00m sacred city express.',
  },
  {
    routeId: 'R-10-R',
    routeNo: 'Route 57-R',
    name: 'Anuradhapura - Colombo (Bastian Mawatha)',
    fromCity: 'Anuradhapura',
    toCity: 'Colombo (Bastian Mawatha)',
    boardingPoints: ['Anuradhapura New Town Terminal', 'Puttalam'],
    droppingPoints: ['Bastian Mawatha Terminal'],
    highwayRoute: 'A8 / Puttalam Corridor',
    distanceKm: '205 km',
    tollFee: 0,
    status: 'Active',
    sourceName: 'Magiya.lk & Dinisuru Line',
    sourceUrl: 'https://magiya.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Return 4h 00m sacred city express.',
  },
  {
    routeId: 'R-11',
    routeNo: 'Route 48-1',
    name: 'Colombo (Bastian Mawatha) - Dambulla',
    fromCity: 'Colombo (Bastian Mawatha)',
    toCity: 'Dambulla',
    boardingPoints: ['Bastian Mawatha Terminal'],
    droppingPoints: ['Kurunegala Central', 'Dambulla Town Stand'],
    highwayRoute: 'A6 Highway',
    distanceKm: '160 km',
    tollFee: 0,
    status: 'Active',
    sourceName: 'BusSeat.lk Listing',
    sourceUrl: 'https://www.busseat.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '3h 15m cultural triangle service.',
  },
  {
    routeId: 'R-12',
    routeNo: 'Route 04',
    name: 'Colombo (Bastian Mawatha) - Mannar',
    fromCity: 'Colombo (Bastian Mawatha)',
    toCity: 'Mannar',
    boardingPoints: ['Bastian Mawatha Terminal'],
    droppingPoints: ['Medawachchiya', 'Mannar Town Terminal'],
    highwayRoute: 'A14 Highway',
    distanceKm: '310 km',
    tollFee: 0,
    status: 'Active',
    sourceName: 'Rathna Travels Listing',
    sourceUrl: 'https://rathnatravels.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '6h 00m North-West express route.',
  },
  {
    routeId: 'R-13',
    routeNo: 'Route 87-V',
    name: 'Colombo (Bastian Mawatha) - Vavuniya',
    fromCity: 'Colombo (Bastian Mawatha)',
    toCity: 'Vavuniya',
    boardingPoints: ['Bastian Mawatha Terminal'],
    droppingPoints: ['Vavuniya Central Terminal'],
    highwayRoute: 'A9 Highway',
    distanceKm: '255 km',
    tollFee: 0,
    status: 'Active',
    sourceName: 'BusSeat.lk Listing',
    sourceUrl: 'https://www.busseat.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '4h 45m Northern gateway express.',
  },
  {
    routeId: 'R-14',
    routeNo: 'Route 87/EX',
    name: 'Jaffna - Galle (MMC) Inter-Provincial Super Luxury Express',
    fromCity: 'Jaffna',
    toCity: 'Galle (MMC)',
    boardingPoints: ['Jaffna Central Stand', 'Kilinochchi', 'Vavuniya Central'],
    droppingPoints: ['Makumbura Multimodal Hub', 'Kottawa Interchange', 'Galle Central Terminal'],
    highwayRoute: 'A9 Northern Highway & Southern Expressway (E01)',
    distanceKm: '510 km',
    tollFee: 420,
    status: 'Active',
    sourceName: 'NCG Express & BusSeat.lk Verified Line',
    sourceUrl: 'https://ncgexpress.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '9h 30m direct inter-provincial super luxury overnight coach from Jaffna to Galle.',
  },
  {
    routeId: 'R-14-R',
    routeNo: 'Route 87/EX-R',
    name: 'Galle (MMC) - Jaffna Inter-Provincial Super Luxury Express',
    fromCity: 'Galle (MMC)',
    toCity: 'Jaffna',
    boardingPoints: ['Galle Central Terminal', 'Kottawa Interchange', 'Makumbura Hub'],
    droppingPoints: ['Vavuniya Central', 'Kilinochchi', 'Jaffna Central Stand'],
    highwayRoute: 'Southern Expressway (E01) & A9 Northern Highway',
    distanceKm: '510 km',
    tollFee: 420,
    status: 'Active',
    sourceName: 'NCG Express & BusSeat.lk Verified Line',
    sourceUrl: 'https://ncgexpress.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '9h 30m direct inter-provincial super luxury coach from Galle to Jaffna.',
  },
  {
    routeId: 'R-15',
    routeNo: 'Route 350 / EX',
    name: 'Galle (MMC) - Kataragama Coastal & Southern Highway',
    fromCity: 'Galle (MMC)',
    toCity: 'Kataragama',
    boardingPoints: ['Galle Central Terminal', 'Matara MMC'],
    droppingPoints: ['Tangalle Bus Stand', 'Ambalantota', 'Hambantota', 'Kataragama Terminal'],
    highwayRoute: 'Southern Expressway Extension & A2 Coastal Highway',
    distanceKm: '145 km',
    tollFee: 300,
    status: 'Active',
    sourceName: 'NTC & Southern Express Consortium',
    sourceUrl: 'https://mmck.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '2h 45m Southern coastal & highway shuttle.',
  },
  {
    routeId: 'R-15-R',
    routeNo: 'Route 350 / EX-R',
    name: 'Kataragama - Galle (MMC) Southern Expressway / Coastal',
    fromCity: 'Kataragama',
    toCity: 'Galle (MMC)',
    boardingPoints: ['Kataragama Terminal', 'Tissamaharama', 'Hambantota', 'Tangalle'],
    droppingPoints: ['Matara MMC', 'Galle Central Terminal'],
    highwayRoute: 'Southern Expressway Extension & A2 Coastal Highway',
    distanceKm: '145 km',
    tollFee: 300,
    status: 'Active',
    sourceName: 'NTC & Southern Express Consortium',
    sourceUrl: 'https://mmck.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Return 2h 45m Southern highway shuttle from Kataragama to Galle.',
  },
  {
    routeId: 'R-16',
    routeNo: 'Route 57/87',
    name: 'Kandy (Goods Shed) - Jaffna Direct Northern Express',
    fromCity: 'Kandy (Goods Shed)',
    toCity: 'Jaffna',
    boardingPoints: ['Kandy Goods Shed Terminal', 'Matale Town', 'Dambulla Town'],
    droppingPoints: ['Anuradhapura Bypass', 'Vavuniya Central', 'Kilinochchi', 'Jaffna Central Stand'],
    highwayRoute: 'A9 Highway Corridor',
    distanceKm: '310 km',
    tollFee: 0,
    status: 'Active',
    sourceName: 'Rathna Travels & NCG Express',
    sourceUrl: 'https://rathnatravels.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '6h 30m direct central to northern highway coach.',
  },
  {
    routeId: 'R-16-R',
    routeNo: 'Route 57/87-R',
    name: 'Jaffna - Kandy (Goods Shed) Direct Northern Express',
    fromCity: 'Jaffna',
    toCity: 'Kandy (Goods Shed)',
    boardingPoints: ['Jaffna Central Stand', 'Kilinochchi', 'Vavuniya Central'],
    droppingPoints: ['Dambulla Town', 'Matale Town', 'Kandy Goods Shed Terminal'],
    highwayRoute: 'A9 Highway Corridor',
    distanceKm: '310 km',
    tollFee: 0,
    status: 'Active',
    sourceName: 'Rathna Travels & NCG Express',
    sourceUrl: 'https://rathnatravels.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Return 6h 30m Jaffna to Kandy express coach.',
  },
  {
    routeId: 'R-17',
    routeNo: 'Route 100/EX',
    name: 'Kandy (Goods Shed) - Galle (MMC) Intercity Expressway',
    fromCity: 'Kandy (Goods Shed)',
    toCity: 'Galle (MMC)',
    boardingPoints: ['Kandy Goods Shed Terminal', 'Peradeniya Junction'],
    droppingPoints: ['Kadawatha Hub', 'Makumbura Hub', 'Galle Central Terminal'],
    highwayRoute: 'Central Expressway (E04) & Southern Expressway (E01)',
    distanceKm: '220 km',
    tollFee: 750,
    status: 'Active',
    sourceName: 'NTC Inter-Provincial Schedule',
    sourceUrl: 'https://www.ntc.gov.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '4h 00m direct expressway link from Kandy to Galle.',
  },
  {
    routeId: 'R-17-R',
    routeNo: 'Route 100/EX-R',
    name: 'Galle (MMC) - Kandy (Goods Shed) Intercity Expressway',
    fromCity: 'Galle (MMC)',
    toCity: 'Kandy (Goods Shed)',
    boardingPoints: ['Galle Central Terminal', 'Kottawa Interchange'],
    droppingPoints: ['Kadawatha Hub', 'Peradeniya Junction', 'Kandy Goods Shed Terminal'],
    highwayRoute: 'Southern Expressway (E01) & Central Expressway (E04)',
    distanceKm: '220 km',
    tollFee: 750,
    status: 'Active',
    sourceName: 'NTC Inter-Provincial Schedule',
    sourceUrl: 'https://www.ntc.gov.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Return 4h 00m direct expressway link from Galle to Kandy.',
  },
  {
    routeId: 'R-18',
    routeNo: 'Route 87/EX-2',
    name: 'Jaffna - Kataragama Inter-Provincial Expressway Line',
    fromCity: 'Jaffna',
    toCity: 'Kataragama',
    boardingPoints: ['Jaffna Central Stand', 'Kilinochchi', 'Vavuniya Central'],
    droppingPoints: ['Makumbura Hub', 'Galle MMC', 'Tangalle', 'Tissamaharama', 'Kataragama Terminal'],
    highwayRoute: 'A9 Northern Highway & Southern Expressway (E01)',
    distanceKm: '585 km',
    tollFee: 850,
    status: 'Active',
    sourceName: 'Superline Travels & NCG Express',
    sourceUrl: 'https://superline.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '10h 30m direct long-distance overnight luxury coach from Jaffna to Kataragama.',
  },
  {
    routeId: 'R-18-R',
    routeNo: 'Route 87/EX-2-R',
    name: 'Kataragama - Jaffna Inter-Provincial Expressway Line',
    fromCity: 'Kataragama',
    toCity: 'Jaffna',
    boardingPoints: ['Kataragama Terminal', 'Tissamaharama', 'Tangalle', 'Galle MMC'],
    droppingPoints: ['Vavuniya Central', 'Kilinochchi', 'Jaffna Central Stand'],
    highwayRoute: 'Southern Expressway (E01) & A9 Northern Highway',
    distanceKm: '585 km',
    tollFee: 850,
    status: 'Active',
    sourceName: 'Superline Travels & NCG Express',
    sourceUrl: 'https://superline.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Return 10h 30m direct long-distance luxury coach from Kataragama to Jaffna.',
  },
];

export const verifiedBuses = [
  {
    busId: 'B-01',
    operatorId: 'OP-01',
    busNo: 'WP ND-6821',
    name: 'Superline Royal Platinum Coach',
    model: 'Volvo B11R Multi-Axle',
    busType: 'Super Luxury Volvo',
    serviceCategory: 'Super Luxury',
    seatLayout: '2+2',
    totalSeats: 40,
    facilities: ['Air Conditioning', 'Reclining Seats', 'USB Charging', 'Wi-Fi', 'TV / Movies', 'Blankets', 'Luggage Boot'],
    rating: 4.9,
    status: 'Active',
    sourceName: 'Superline Travels Official Fleet',
    sourceUrl: 'https://superline.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Flagship 40-seat Volvo coach.',
  },
  {
    busId: 'B-02',
    operatorId: 'OP-01',
    busNo: 'WP ND-7194',
    name: 'Superline VIP Sleeper Cabin',
    model: 'Yutong ZK6122H VIP 2+1',
    busType: 'Super Luxury VIP Sleeper',
    serviceCategory: 'Super Luxury',
    seatLayout: '2+1',
    totalSeats: 28,
    facilities: ['Air Conditioning', 'VIP Reclining Seats', 'Personal Screen', 'USB Charging', 'Wi-Fi', 'Curtains', 'Blanket & Pillow'],
    rating: 4.95,
    status: 'Active',
    sourceName: 'Superline.lk VIP Fleet',
    sourceUrl: 'https://superline.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '28-seat 2+1 VIP executive suite layout.',
  },
  {
    busId: 'B-03',
    operatorId: 'OP-02',
    busNo: 'WP NB-9245',
    name: 'NCG Royal Cruiser',
    model: 'Yutong ZK6122H High-Deck',
    busType: 'Super Luxury AC',
    serviceCategory: 'Super Luxury',
    seatLayout: '2+2',
    totalSeats: 44,
    facilities: ['Air Conditioning', 'Reclining Seats', 'USB Ports', 'Reading Lights', 'Audio System', 'Luggage Space'],
    rating: 4.8,
    status: 'Active',
    sourceName: 'NCG Express Official',
    sourceUrl: 'https://ncgexpress.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '44-seat intercity luxury coach.',
  },
  {
    busId: 'B-04',
    operatorId: 'OP-03',
    busNo: 'NP ND-4412',
    name: 'Rathna Crown Express',
    model: 'Ashok Leyland Viking 222 AC',
    busType: 'Super Luxury Coach',
    serviceCategory: 'Super Luxury',
    seatLayout: '2+2',
    totalSeats: 42,
    facilities: ['Air Conditioning', 'Reclining Seats', 'USB Charging', 'Music System', 'Underfloor Luggage'],
    rating: 4.7,
    status: 'Active',
    sourceName: 'Rathna Travels Fleet',
    sourceUrl: 'https://rathnatravels.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '42-seat Northern corridor coach.',
  },
  {
    busId: 'B-05',
    operatorId: 'OP-04',
    busNo: 'WP NC-3318',
    name: 'Dinisuru AC Liner',
    model: 'Higer KLQ6129 Luxury',
    busType: 'Luxury AC',
    serviceCategory: 'Luxury',
    seatLayout: '2+2',
    totalSeats: 40,
    facilities: ['Air Conditioning', 'Reclining Seats', 'Luggage Rack', 'Digital Clock'],
    rating: 4.6,
    status: 'Active',
    sourceName: 'Magiya.lk Verified Fleet',
    sourceUrl: 'https://magiya.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '40-seat AC express coach.',
  },
  {
    busId: 'B-06',
    operatorId: 'OP-05',
    busNo: 'SP ND-5521',
    name: 'Southern Highway Express Liner 01',
    model: 'King Long XMQ6129',
    busType: 'Expressway Luxury AC',
    serviceCategory: 'Luxury',
    seatLayout: '2+2',
    totalSeats: 42,
    facilities: ['Air Conditioning', 'Reclining Seats', 'Expressway Pass', 'Luggage Space'],
    rating: 4.75,
    status: 'Active',
    sourceName: 'MMCK Southern Network',
    sourceUrl: 'https://mmck.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '42-seat highway shuttle coach.',
  },
  {
    busId: 'B-07',
    operatorId: 'OP-05',
    busNo: 'SP ND-8834',
    name: 'Southern Highway Express Liner 02',
    model: 'King Long XMQ6129',
    busType: 'Expressway Luxury AC',
    serviceCategory: 'Luxury',
    seatLayout: '2+2',
    totalSeats: 42,
    facilities: ['Air Conditioning', 'Reclining Seats', 'Expressway Pass', 'Luggage Space'],
    rating: 4.75,
    status: 'Active',
    sourceName: 'MMCK Southern Network',
    sourceUrl: 'https://mmck.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '42-seat highway shuttle coach.',
  },
  {
    busId: 'B-08',
    operatorId: 'OP-06',
    busNo: 'EP ND-2910',
    name: 'SPS Eastern Platinum',
    model: 'Yutong ZK6122H High-Deck',
    busType: 'Super Luxury AC',
    serviceCategory: 'Super Luxury',
    seatLayout: '2+2',
    totalSeats: 40,
    facilities: ['Air Conditioning', 'Reclining Seats', 'USB Charging', 'Movie Screen', 'Blankets'],
    rating: 4.85,
    status: 'Active',
    sourceName: 'BusSeat.lk & SPS Listing',
    sourceUrl: 'https://www.busseat.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '40-seat Batticaloa express coach.',
  },
  {
    busId: 'B-09',
    operatorId: 'OP-07',
    busNo: 'NP ND-8102',
    name: 'North West Crown VIP Sleeper',
    model: 'Volvo B11R 2+1 Executive Suite',
    busType: 'Premium VIP Sleeper',
    serviceCategory: 'Premium',
    seatLayout: '2+1',
    totalSeats: 28,
    facilities: ['Air Conditioning', '2+1 Single VIP Seats', 'Personal Entertainment Screen', 'Wi-Fi', 'USB Charging', 'Blanket & Refreshments'],
    rating: 4.98,
    status: 'Active',
    sourceName: 'BusSeat.lk Premium Listing',
    sourceUrl: 'https://www.busseat.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '28-seat 2+1 VIP single/pair layout.',
  },
  {
    busId: 'B-10',
    operatorId: 'OP-05',
    busNo: 'CP ND-1980',
    name: 'Central Expressway Kandy Royal',
    model: 'Higer KLQ6119 AC',
    busType: 'Expressway Luxury AC',
    serviceCategory: 'Luxury',
    seatLayout: '2+2',
    totalSeats: 40,
    facilities: ['Air Conditioning', 'Reclining Seats', 'USB Charging', 'Overhead Rack'],
    rating: 4.7,
    status: 'Active',
    sourceName: 'KMC Network & NTC',
    sourceUrl: 'https://www.ntc.gov.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: '40-seat Kandy express shuttle.',
  },
];

export const verifiedSchedules = [
  {
    scheduleId: 'S-01',
    busId: 'B-06',
    routeId: 'R-01',
    departureTime: '06:00 AM',
    arrivalTime: '07:30 AM',
    duration: '1h 30m',
    operatingDays: 'Daily',
    fare: 420,
    currency: 'LKR',
    reservedSeats: ['A1', 'A2', 'B1'],
    status: 'Active',
    sourceName: 'MMCK Official Schedule',
    sourceUrl: 'https://mmck.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Morning Galle expressway shuttle.',
  },
  {
    scheduleId: 'S-01-R',
    busId: 'B-06',
    routeId: 'R-01-R',
    departureTime: '08:30 AM',
    arrivalTime: '10:00 AM',
    duration: '1h 30m',
    operatingDays: 'Daily',
    fare: 420,
    currency: 'LKR',
    reservedSeats: [],
    status: 'Active',
    sourceName: 'MMCK Official Schedule',
    sourceUrl: 'https://mmck.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Return Galle to Colombo expressway shuttle.',
  },
  {
    scheduleId: 'S-02',
    busId: 'B-06',
    routeId: 'R-01',
    departureTime: '08:30 AM',
    arrivalTime: '10:00 AM',
    duration: '1h 30m',
    operatingDays: 'Daily',
    fare: 420,
    currency: 'LKR',
    reservedSeats: [],
    status: 'Active',
    sourceName: 'MMCK Official Schedule',
    sourceUrl: 'https://mmck.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Mid-morning Galle expressway shuttle.',
  },
  {
    scheduleId: 'S-03',
    busId: 'B-01',
    routeId: 'R-01',
    departureTime: '02:00 PM',
    arrivalTime: '03:30 PM',
    duration: '1h 30m',
    operatingDays: 'Daily',
    fare: 450,
    currency: 'LKR',
    reservedSeats: ['A3', 'A4'],
    status: 'Active',
    sourceName: 'Superline Travels Schedule',
    sourceUrl: 'https://superline.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Afternoon Volvo B11R Galle service.',
  },
  {
    scheduleId: 'S-04',
    busId: 'B-07',
    routeId: 'R-02',
    departureTime: '06:30 AM',
    arrivalTime: '08:30 AM',
    duration: '2h 00m',
    operatingDays: 'Daily',
    fare: 550,
    currency: 'LKR',
    reservedSeats: ['B3', 'B4', 'C1'],
    status: 'Active',
    sourceName: 'MMCK Official Schedule',
    sourceUrl: 'https://mmck.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Morning Matara expressway shuttle.',
  },
  {
    scheduleId: 'S-04-R',
    busId: 'B-07',
    routeId: 'R-02-R',
    departureTime: '09:30 AM',
    arrivalTime: '11:30 AM',
    duration: '2h 00m',
    operatingDays: 'Daily',
    fare: 550,
    currency: 'LKR',
    reservedSeats: [],
    status: 'Active',
    sourceName: 'MMCK Official Schedule',
    sourceUrl: 'https://mmck.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Return Matara to Colombo expressway shuttle.',
  },
  {
    scheduleId: 'S-05',
    busId: 'B-07',
    routeId: 'R-02',
    departureTime: '01:30 PM',
    arrivalTime: '03:30 PM',
    duration: '2h 00m',
    operatingDays: 'Daily',
    fare: 550,
    currency: 'LKR',
    reservedSeats: [],
    status: 'Active',
    sourceName: 'MMCK Official Schedule',
    sourceUrl: 'https://mmck.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Afternoon Matara expressway shuttle.',
  },
  {
    scheduleId: 'S-06',
    busId: 'B-03',
    routeId: 'R-03',
    departureTime: '07:00 AM',
    arrivalTime: '10:00 AM',
    duration: '3h 00m',
    operatingDays: 'Daily',
    fare: 950,
    currency: 'LKR',
    reservedSeats: ['A1', 'C2'],
    status: 'Active',
    sourceName: 'NCG Express Schedule',
    sourceUrl: 'https://ncgexpress.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Hambantota direct expressway service.',
  },
  {
    scheduleId: 'S-07',
    busId: 'B-01',
    routeId: 'R-04',
    departureTime: '05:30 AM',
    arrivalTime: '09:15 AM',
    duration: '3h 45m',
    operatingDays: 'Daily',
    fare: 1150,
    currency: 'LKR',
    reservedSeats: ['A1', 'A2', 'B1', 'B2'],
    status: 'Active',
    sourceName: 'Superline Travels Schedule',
    sourceUrl: 'https://superline.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Kataragama direct Volvo express.',
  },
  {
    scheduleId: 'S-08',
    busId: 'B-10',
    routeId: 'R-05',
    departureTime: '07:15 AM',
    arrivalTime: '09:45 AM',
    duration: '2h 30m',
    operatingDays: 'Daily',
    fare: 650,
    currency: 'LKR',
    reservedSeats: [],
    status: 'Active',
    sourceName: 'NTC Schedule',
    sourceUrl: 'https://www.ntc.gov.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Kandy morning intercity express.',
  },
  {
    scheduleId: 'S-08-R',
    busId: 'B-10',
    routeId: 'R-05-R',
    departureTime: '02:00 PM',
    arrivalTime: '04:30 PM',
    duration: '2h 30m',
    operatingDays: 'Daily',
    fare: 650,
    currency: 'LKR',
    reservedSeats: [],
    status: 'Active',
    sourceName: 'NTC Schedule',
    sourceUrl: 'https://www.ntc.gov.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Return Kandy to Kadawatha express.',
  },
  {
    scheduleId: 'S-09',
    busId: 'B-01',
    routeId: 'R-06',
    departureTime: '06:00 AM',
    arrivalTime: '11:30 AM',
    duration: '5h 30m',
    operatingDays: 'Daily',
    fare: 1950,
    currency: 'LKR',
    reservedSeats: ['A1', 'C1'],
    status: 'Active',
    sourceName: 'Superline.lk Schedule',
    sourceUrl: 'https://superline.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Badulla morning Volvo highway liner (Colombo to Badulla).',
  },
  {
    scheduleId: 'S-09-R',
    busId: 'B-01',
    routeId: 'R-06-R',
    departureTime: '01:00 PM',
    arrivalTime: '06:30 PM',
    duration: '5h 30m',
    operatingDays: 'Daily',
    fare: 1950,
    currency: 'LKR',
    reservedSeats: ['B1', 'B2'],
    status: 'Active',
    sourceName: 'Superline.lk Schedule',
    sourceUrl: 'https://superline.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Badulla to Colombo return Volvo highway liner.',
  },
  {
    scheduleId: 'S-10',
    busId: 'B-02',
    routeId: 'R-07',
    departureTime: '09:30 PM',
    arrivalTime: '05:00 AM',
    duration: '7h 30m',
    operatingDays: 'Daily',
    fare: 3500,
    currency: 'LKR',
    reservedSeats: ['A1', 'A2', 'B1', 'C1'],
    status: 'Active',
    sourceName: 'Superline.lk 2+1 VIP Listing',
    sourceUrl: 'https://superline.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Jaffna 2+1 VIP Sleeper overnight coach.',
  },
  {
    scheduleId: 'S-10-R',
    busId: 'B-02',
    routeId: 'R-07-R',
    departureTime: '08:30 PM',
    arrivalTime: '04:00 AM',
    duration: '7h 30m',
    operatingDays: 'Daily',
    fare: 3500,
    currency: 'LKR',
    reservedSeats: [],
    status: 'Active',
    sourceName: 'Superline.lk 2+1 VIP Listing',
    sourceUrl: 'https://superline.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Jaffna to Colombo 2+1 VIP Sleeper return coach.',
  },
  {
    scheduleId: 'S-11',
    busId: 'B-03',
    routeId: 'R-07',
    departureTime: '10:00 PM',
    arrivalTime: '05:30 AM',
    duration: '7h 30m',
    operatingDays: 'Daily',
    fare: 3200,
    currency: 'LKR',
    reservedSeats: ['C3', 'C4'],
    status: 'Active',
    sourceName: 'NCG Express Schedule',
    sourceUrl: 'https://ncgexpress.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Jaffna Royal overnight high-deck coach.',
  },
  {
    scheduleId: 'S-12',
    busId: 'B-04',
    routeId: 'R-07',
    departureTime: '08:00 AM',
    arrivalTime: '03:30 PM',
    duration: '7h 30m',
    operatingDays: 'Daily',
    fare: 3200,
    currency: 'LKR',
    reservedSeats: [],
    status: 'Active',
    sourceName: 'Rathna Travels Schedule',
    sourceUrl: 'https://rathnatravels.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Jaffna daytime luxury coach.',
  },
  {
    scheduleId: 'S-13',
    busId: 'B-01',
    routeId: 'R-08',
    departureTime: '10:30 PM',
    arrivalTime: '04:00 AM',
    duration: '5h 30m',
    operatingDays: 'Daily',
    fare: 2400,
    currency: 'LKR',
    reservedSeats: ['A1'],
    status: 'Active',
    sourceName: 'Superline.lk Schedule',
    sourceUrl: 'https://superline.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Trincomalee overnight Volvo B11R.',
  },
  {
    scheduleId: 'S-13-R',
    busId: 'B-01',
    routeId: 'R-08-R',
    departureTime: '09:30 PM',
    arrivalTime: '03:00 AM',
    duration: '5h 30m',
    operatingDays: 'Daily',
    fare: 2400,
    currency: 'LKR',
    reservedSeats: [],
    status: 'Active',
    sourceName: 'Superline.lk Schedule',
    sourceUrl: 'https://superline.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Trincomalee to Colombo return Volvo coach.',
  },
  {
    scheduleId: 'S-14',
    busId: 'B-08',
    routeId: 'R-09',
    departureTime: '09:00 PM',
    arrivalTime: '03:30 AM',
    duration: '6h 30m',
    operatingDays: 'Daily',
    fare: 2600,
    currency: 'LKR',
    reservedSeats: ['B1', 'B2'],
    status: 'Active',
    sourceName: 'SPS Travels Schedule',
    sourceUrl: 'https://www.busseat.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Batticaloa overnight Eastern Platinum coach.',
  },
  {
    scheduleId: 'S-14-R',
    busId: 'B-08',
    routeId: 'R-09-R',
    departureTime: '08:30 PM',
    arrivalTime: '03:00 AM',
    duration: '6h 30m',
    operatingDays: 'Daily',
    fare: 2600,
    currency: 'LKR',
    reservedSeats: [],
    status: 'Active',
    sourceName: 'SPS Travels Schedule',
    sourceUrl: 'https://www.busseat.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Batticaloa to Colombo return coach.',
  },
  {
    scheduleId: 'S-15',
    busId: 'B-05',
    routeId: 'R-10',
    departureTime: '07:30 AM',
    arrivalTime: '11:30 AM',
    duration: '4h 00m',
    operatingDays: 'Daily',
    fare: 1800,
    currency: 'LKR',
    reservedSeats: [],
    status: 'Active',
    sourceName: 'Magiya.lk & Dinisuru Line',
    sourceUrl: 'https://magiya.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Anuradhapura morning sacred city express.',
  },
  {
    scheduleId: 'S-15-R',
    busId: 'B-05',
    routeId: 'R-10-R',
    departureTime: '02:00 PM',
    arrivalTime: '06:00 PM',
    duration: '4h 00m',
    operatingDays: 'Daily',
    fare: 1800,
    currency: 'LKR',
    reservedSeats: [],
    status: 'Active',
    sourceName: 'Magiya.lk & Dinisuru Line',
    sourceUrl: 'https://magiya.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Anuradhapura to Colombo return express.',
  },
  {
    scheduleId: 'S-16',
    busId: 'B-03',
    routeId: 'R-11',
    departureTime: '08:00 AM',
    arrivalTime: '11:15 AM',
    duration: '3h 15m',
    operatingDays: 'Daily',
    fare: 1450,
    currency: 'LKR',
    reservedSeats: [],
    status: 'Active',
    sourceName: 'BusSeat.lk Listing',
    sourceUrl: 'https://www.busseat.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Dambulla morning cultural triangle express.',
  },
  {
    scheduleId: 'S-17',
    busId: 'B-04',
    routeId: 'R-12',
    departureTime: '09:00 PM',
    arrivalTime: '03:00 AM',
    duration: '6h 00m',
    operatingDays: 'Daily',
    fare: 2750,
    currency: 'LKR',
    reservedSeats: ['A1', 'A2'],
    status: 'Active',
    sourceName: 'Rathna Travels Schedule',
    sourceUrl: 'https://rathnatravels.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Mannar overnight express coach.',
  },
  {
    scheduleId: 'S-18',
    busId: 'B-09',
    routeId: 'R-13',
    departureTime: '09:15 PM',
    arrivalTime: '02:00 AM',
    duration: '4h 45m',
    operatingDays: 'Daily',
    fare: 2100,
    currency: 'LKR',
    reservedSeats: ['A1'],
    status: 'Active',
    sourceName: 'BusSeat.lk 2+1 Listing',
    sourceUrl: 'https://www.busseat.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Vavuniya 2+1 VIP sleeper express.',
  },
  {
    scheduleId: 'S-19',
    busId: 'B-09',
    routeId: 'R-07',
    departureTime: '10:30 PM',
    arrivalTime: '06:00 AM',
    duration: '7h 30m',
    operatingDays: 'Daily',
    fare: 3500,
    currency: 'LKR',
    reservedSeats: ['A1', 'B1', 'C1'],
    status: 'Active',
    sourceName: 'North West Express 2+1 Listing',
    sourceUrl: 'https://www.busseat.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Jaffna North West VIP Crown Class sleeper coach.',
  },
  {
    scheduleId: 'S-20',
    busId: 'B-02',
    routeId: 'R-14',
    departureTime: '08:00 PM',
    arrivalTime: '05:30 AM',
    duration: '9h 30m',
    operatingDays: 'Daily',
    fare: 4200,
    currency: 'LKR',
    reservedSeats: ['A1', 'B1'],
    status: 'Active',
    sourceName: 'NCG Express & BusSeat.lk Inter-Provincial',
    sourceUrl: 'https://ncgexpress.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Direct 2+1 VIP Sleeper overnight coach from Jaffna to Galle.',
  },
  {
    scheduleId: 'S-20-R',
    busId: 'B-02',
    routeId: 'R-14-R',
    departureTime: '07:30 PM',
    arrivalTime: '05:00 AM',
    duration: '9h 30m',
    operatingDays: 'Daily',
    fare: 4200,
    currency: 'LKR',
    reservedSeats: [],
    status: 'Active',
    sourceName: 'NCG Express & BusSeat.lk Inter-Provincial',
    sourceUrl: 'https://ncgexpress.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Direct 2+1 VIP Sleeper coach from Galle to Jaffna.',
  },
  {
    scheduleId: 'S-21',
    busId: 'B-06',
    routeId: 'R-15',
    departureTime: '07:00 AM',
    arrivalTime: '09:45 AM',
    duration: '2h 45m',
    operatingDays: 'Daily',
    fare: 680,
    currency: 'LKR',
    reservedSeats: [],
    status: 'Active',
    sourceName: 'NTC & Southern Express Consortium',
    sourceUrl: 'https://mmck.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Galle to Kataragama highway & coastal shuttle.',
  },
  {
    scheduleId: 'S-21-R',
    busId: 'B-06',
    routeId: 'R-15-R',
    departureTime: '01:30 PM',
    arrivalTime: '04:15 PM',
    duration: '2h 45m',
    operatingDays: 'Daily',
    fare: 680,
    currency: 'LKR',
    reservedSeats: [],
    status: 'Active',
    sourceName: 'NTC & Southern Express Consortium',
    sourceUrl: 'https://mmck.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Kataragama to Galle highway & coastal shuttle.',
  },
  {
    scheduleId: 'S-22',
    busId: 'B-04',
    routeId: 'R-16',
    departureTime: '08:30 AM',
    arrivalTime: '03:00 PM',
    duration: '6h 30m',
    operatingDays: 'Daily',
    fare: 2800,
    currency: 'LKR',
    reservedSeats: [],
    status: 'Active',
    sourceName: 'Rathna Travels & NCG Express',
    sourceUrl: 'https://rathnatravels.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Kandy to Jaffna daytime express coach.',
  },
  {
    scheduleId: 'S-22-R',
    busId: 'B-04',
    routeId: 'R-16-R',
    departureTime: '09:00 PM',
    arrivalTime: '03:30 AM',
    duration: '6h 30m',
    operatingDays: 'Daily',
    fare: 2800,
    currency: 'LKR',
    reservedSeats: [],
    status: 'Active',
    sourceName: 'Rathna Travels & NCG Express',
    sourceUrl: 'https://rathnatravels.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Jaffna to Kandy overnight express coach.',
  },
  {
    scheduleId: 'S-23',
    busId: 'B-10',
    routeId: 'R-17',
    departureTime: '06:45 AM',
    arrivalTime: '10:45 AM',
    duration: '4h 00m',
    operatingDays: 'Daily',
    fare: 1100,
    currency: 'LKR',
    reservedSeats: [],
    status: 'Active',
    sourceName: 'NTC Inter-Provincial Schedule',
    sourceUrl: 'https://www.ntc.gov.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Kandy to Galle direct expressway shuttle.',
  },
  {
    scheduleId: 'S-23-R',
    busId: 'B-10',
    routeId: 'R-17-R',
    departureTime: '01:15 PM',
    arrivalTime: '05:15 PM',
    duration: '4h 00m',
    operatingDays: 'Daily',
    fare: 1100,
    currency: 'LKR',
    reservedSeats: [],
    status: 'Active',
    sourceName: 'NTC Inter-Provincial Schedule',
    sourceUrl: 'https://www.ntc.gov.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Galle to Kandy direct expressway shuttle.',
  },
  {
    scheduleId: 'S-24',
    busId: 'B-02',
    routeId: 'R-18',
    departureTime: '07:00 PM',
    arrivalTime: '05:30 AM',
    duration: '10h 30m',
    operatingDays: 'Daily',
    fare: 4600,
    currency: 'LKR',
    reservedSeats: ['A1', 'B1'],
    status: 'Active',
    sourceName: 'Superline Travels & NCG Express',
    sourceUrl: 'https://superline.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Direct 2+1 VIP Sleeper overnight coach from Jaffna to Kataragama.',
  },
  {
    scheduleId: 'S-24-R',
    busId: 'B-02',
    routeId: 'R-18-R',
    departureTime: '06:00 PM',
    arrivalTime: '04:30 AM',
    duration: '10h 30m',
    operatingDays: 'Daily',
    fare: 4600,
    currency: 'LKR',
    reservedSeats: [],
    status: 'Active',
    sourceName: 'Superline Travels & NCG Express',
    sourceUrl: 'https://superline.lk',
    lastVerifiedDate: '2026-08-26',
    dataStatus: 'Verified',
    notes: 'Direct 2+1 VIP Sleeper overnight coach from Kataragama to Jaffna.',
  },
];

export const verifiedUsers = [
  {
    userId: 'admin_100',
    name: 'Supun Perera',
    email: 'admin@highwayexpress.lk',
    password: 'admin123',
    role: 'admin',
    adminPermissions: [
      'manage_users',
      'manage_buses',
      'manage_routes',
      'manage_schedules',
      'manage_conductors',
      'manage_bookings',
      'manage_finances',
      'view_reports',
      'view_logs',
    ],
    phone: '+94 77 123 4567',
    walletBalance: 0,
    status: 'Active',
  },
  {
    userId: 'admin_101',
    name: 'Executive SuperAdministrator',
    email: 'admin@lankaexpressway.lk',
    password: 'admin123',
    role: 'superadmin',
    adminPermissions: [
      'manage_users',
      'manage_buses',
      'manage_routes',
      'manage_schedules',
      'manage_conductors',
      'manage_bookings',
      'manage_finances',
      'view_reports',
      'view_logs',
      'manage_admins',
    ],
    phone: '+94 77 999 8888',
    walletBalance: 0,
    status: 'Active',
  },
  {
    userId: 'cust_200',
    name: 'Tharidu Silva',
    email: 'customer@gmail.com',
    password: 'user123',
    role: 'user',
    phone: '+94 71 987 6543',
    walletBalance: 0,
    status: 'Active',
  },
  {
    userId: 'cust_241',
    name: 'Hasini Sithara',
    email: 'hasini@gmail.com',
    password: 'user123',
    role: 'user',
    phone: '+94 77 456 7890',
    walletBalance: 0,
    status: 'Active',
  },
  {
    userId: 'cond_301',
    employeeId: 'EMP-101',
    name: 'Nimal Perera',
    email: 'conductor@lankaexpressway.lk',
    password: 'password123',
    role: 'conductor',
    assignedBuses: ['B-01', 'B-02'],
    conductorPermissions: {
      maxBusesAllowed: 2,
      canScanQR: true,
      canIssueTickets: true,
      canCancelBoarding: true,
    },
    phone: '+94 77 345 6789',
    walletBalance: 0,
    status: 'Active',
  },
  {
    userId: 'cond_302',
    employeeId: 'EMP-102',
    name: 'Sunil Shantha',
    email: 'sunil.conductor@lankaexpressway.lk',
    password: 'password123',
    role: 'conductor',
    assignedBuses: ['B-03'],
    conductorPermissions: {
      maxBusesAllowed: 2,
      canScanQR: true,
      canIssueTickets: true,
      canCancelBoarding: true,
    },
    phone: '+94 77 987 1234',
    walletBalance: 0,
    status: 'Active',
  },
];
